/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_appsync_graphqlEndpoint:
    "https://y5wkmj2jajbe5cz4tfanuvvjem.appsync-api.eu-north-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-north-1",
  aws_appsync_authenticationType: "AWS_LAMBDA",
};

export default awsmobile;
